#!/usr/bin/env python3
##
## EPITECH PROJECT, 2019
## 102architect_2019
## File description:
## 102architect by clément fleur and arthur perrot
##

import sys
import math
from check import *

def main():
    if len(sys.argv) == 2 and (sys.argv[1] == "-h"):
        help()
    check_error(sys.argv)
    i = 1
    while i < len(sys.argv):
        check_type(i, sys.argv)
        i = i + 1
       

if __name__ == "__main__":
    main()