#!/usr/bin/env python3
##
## EPITECH PROJECT, 2019
## 108trigo_2019
## File description:
## main
##

import sys
import math
from trigo_calcul import *

def help():
    if len(sys.argv) >= 2 and (sys.argv[1] == "-h"):
        print("USAGE")
        print("    ./108trigo fun a0 a1 a2 ...\n")
        print("DESCRIPTION")
        print("    fun   function to be applied, among at least ", end="")
        print("“EXP”, “COS”, “SIN”, “COSH” and “SINH”")
        print("    ai    coeficients of the matrix")
        sys.exit(84)

def check_args_to_float():
    try:
        counter = 2
        while counter < len(sys.argv):
            float(sys.argv[counter])
            counter = counter + 1
    except ValueError:
        print ("Please check your arguments, or see -h")
        sys.exit(84)
    return 0

def function_switcher():
    i = 0
    arg_list = ["EXP", "COS", "SIN", "COSH", "SINH"]
    func = [my_exp, my_cos, my_sin, my_cosh, my_sinh]
    while i < 5:
        if sys.argv[1] == arg_list[i]:
            func[i]()
        i = i + 1

def main():
    help()
    if len(sys.argv) <= 4:
        print("Error : Not enough arguments. Please check")
        sys.exit(84)
    if sys.argv[1] not in ["EXP", "COS", "SIN", "COSH", "SINH"]:
        print("Error : Function name incorrect. please see -h")
        sys.exit(84)
    check_args_to_float()
    function_switcher()
    print(sys.argv[2:])

if __name__ == "__main__":
    main()